// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core_proto.proto

#ifndef PROTOBUF_INCLUDED_core_5fproto_2eproto
#define PROTOBUF_INCLUDED_core_5fproto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_core_5fproto_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_core_5fproto_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_core_5fproto_2eproto();
class SSHeartBeat;
class SSHeartBeatDefaultTypeInternal;
extern SSHeartBeatDefaultTypeInternal _SSHeartBeat_default_instance_;
namespace google {
namespace protobuf {
template<> ::SSHeartBeat* Arena::CreateMaybeMessage<::SSHeartBeat>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class SSHeartBeat final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SSHeartBeat) */ {
 public:
  SSHeartBeat();
  virtual ~SSHeartBeat();

  SSHeartBeat(const SSHeartBeat& from);

  inline SSHeartBeat& operator=(const SSHeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SSHeartBeat(SSHeartBeat&& from) noexcept
    : SSHeartBeat() {
    *this = ::std::move(from);
  }

  inline SSHeartBeat& operator=(SSHeartBeat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SSHeartBeat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SSHeartBeat* internal_default_instance() {
    return reinterpret_cast<const SSHeartBeat*>(
               &_SSHeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SSHeartBeat* other);
  friend void swap(SSHeartBeat& a, SSHeartBeat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SSHeartBeat* New() const final {
    return CreateMaybeMessage<SSHeartBeat>(nullptr);
  }

  SSHeartBeat* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SSHeartBeat>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SSHeartBeat& from);
  void MergeFrom(const SSHeartBeat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSHeartBeat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 commitlogindex = 2;
  void clear_commitlogindex();
  static const int kCommitlogindexFieldNumber = 2;
  ::google::protobuf::uint64 commitlogindex() const;
  void set_commitlogindex(::google::protobuf::uint64 value);

  // uint32 nodeid = 1;
  void clear_nodeid();
  static const int kNodeidFieldNumber = 1;
  ::google::protobuf::uint32 nodeid() const;
  void set_nodeid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:SSHeartBeat)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 commitlogindex_;
  ::google::protobuf::uint32 nodeid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_core_5fproto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SSHeartBeat

// uint32 nodeid = 1;
inline void SSHeartBeat::clear_nodeid() {
  nodeid_ = 0u;
}
inline ::google::protobuf::uint32 SSHeartBeat::nodeid() const {
  // @@protoc_insertion_point(field_get:SSHeartBeat.nodeid)
  return nodeid_;
}
inline void SSHeartBeat::set_nodeid(::google::protobuf::uint32 value) {
  
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:SSHeartBeat.nodeid)
}

// uint64 commitlogindex = 2;
inline void SSHeartBeat::clear_commitlogindex() {
  commitlogindex_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SSHeartBeat::commitlogindex() const {
  // @@protoc_insertion_point(field_get:SSHeartBeat.commitlogindex)
  return commitlogindex_;
}
inline void SSHeartBeat::set_commitlogindex(::google::protobuf::uint64 value) {
  
  commitlogindex_ = value;
  // @@protoc_insertion_point(field_set:SSHeartBeat.commitlogindex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_core_5fproto_2eproto
