// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core_proto.proto

#ifndef PROTOBUF_INCLUDED_core_5fproto_2eproto
#define PROTOBUF_INCLUDED_core_5fproto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_core_5fproto_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_core_5fproto_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_core_5fproto_2eproto();
namespace core {
class MsgBody;
class MsgBodyDefaultTypeInternal;
extern MsgBodyDefaultTypeInternal _MsgBody_default_instance_;
class MsgHead;
class MsgHeadDefaultTypeInternal;
extern MsgHeadDefaultTypeInternal _MsgHead_default_instance_;
class ReqVote;
class ReqVoteDefaultTypeInternal;
extern ReqVoteDefaultTypeInternal _ReqVote_default_instance_;
class RspVote;
class RspVoteDefaultTypeInternal;
extern RspVoteDefaultTypeInternal _RspVote_default_instance_;
}  // namespace core
namespace google {
namespace protobuf {
template<> ::core::MsgBody* Arena::CreateMaybeMessage<::core::MsgBody>(Arena*);
template<> ::core::MsgHead* Arena::CreateMaybeMessage<::core::MsgHead>(Arena*);
template<> ::core::ReqVote* Arena::CreateMaybeMessage<::core::ReqVote>(Arena*);
template<> ::core::RspVote* Arena::CreateMaybeMessage<::core::RspVote>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace core {

// ===================================================================

class ReqVote final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:core.ReqVote) */ {
 public:
  ReqVote();
  virtual ~ReqVote();

  ReqVote(const ReqVote& from);

  inline ReqVote& operator=(const ReqVote& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqVote(ReqVote&& from) noexcept
    : ReqVote() {
    *this = ::std::move(from);
  }

  inline ReqVote& operator=(ReqVote&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ReqVote& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqVote* internal_default_instance() {
    return reinterpret_cast<const ReqVote*>(
               &_ReqVote_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReqVote* other);
  friend void swap(ReqVote& a, ReqVote& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqVote* New() const final {
    return CreateMaybeMessage<ReqVote>(nullptr);
  }

  ReqVote* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqVote>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqVote& from);
  void MergeFrom(const ReqVote& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqVote* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 Term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint32 term() const;
  void set_term(::google::protobuf::uint32 value);

  // uint32 NodeId = 2;
  void clear_nodeid();
  static const int kNodeIdFieldNumber = 2;
  ::google::protobuf::uint32 nodeid() const;
  void set_nodeid(::google::protobuf::uint32 value);

  // uint64 CommitLogIndex = 3;
  void clear_commitlogindex();
  static const int kCommitLogIndexFieldNumber = 3;
  ::google::protobuf::uint64 commitlogindex() const;
  void set_commitlogindex(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:core.ReqVote)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 term_;
  ::google::protobuf::uint32 nodeid_;
  ::google::protobuf::uint64 commitlogindex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_core_5fproto_2eproto;
};
// -------------------------------------------------------------------

class RspVote final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:core.RspVote) */ {
 public:
  RspVote();
  virtual ~RspVote();

  RspVote(const RspVote& from);

  inline RspVote& operator=(const RspVote& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RspVote(RspVote&& from) noexcept
    : RspVote() {
    *this = ::std::move(from);
  }

  inline RspVote& operator=(RspVote&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RspVote& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RspVote* internal_default_instance() {
    return reinterpret_cast<const RspVote*>(
               &_RspVote_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(RspVote* other);
  friend void swap(RspVote& a, RspVote& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RspVote* New() const final {
    return CreateMaybeMessage<RspVote>(nullptr);
  }

  RspVote* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RspVote>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RspVote& from);
  void MergeFrom(const RspVote& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RspVote* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sint32 Result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // uint32 Term = 2;
  void clear_term();
  static const int kTermFieldNumber = 2;
  ::google::protobuf::uint32 term() const;
  void set_term(::google::protobuf::uint32 value);

  // uint32 NodeId = 3;
  void clear_nodeid();
  static const int kNodeIdFieldNumber = 3;
  ::google::protobuf::uint32 nodeid() const;
  void set_nodeid(::google::protobuf::uint32 value);

  // uint32 LeaderId = 4;
  void clear_leaderid();
  static const int kLeaderIdFieldNumber = 4;
  ::google::protobuf::uint32 leaderid() const;
  void set_leaderid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:core.RspVote)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::uint32 term_;
  ::google::protobuf::uint32 nodeid_;
  ::google::protobuf::uint32 leaderid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_core_5fproto_2eproto;
};
// -------------------------------------------------------------------

class MsgHead final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:core.MsgHead) */ {
 public:
  MsgHead();
  virtual ~MsgHead();

  MsgHead(const MsgHead& from);

  inline MsgHead& operator=(const MsgHead& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsgHead(MsgHead&& from) noexcept
    : MsgHead() {
    *this = ::std::move(from);
  }

  inline MsgHead& operator=(MsgHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const MsgHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgHead* internal_default_instance() {
    return reinterpret_cast<const MsgHead*>(
               &_MsgHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(MsgHead* other);
  friend void swap(MsgHead& a, MsgHead& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsgHead* New() const final {
    return CreateMaybeMessage<MsgHead>(nullptr);
  }

  MsgHead* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MsgHead>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MsgHead& from);
  void MergeFrom(const MsgHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 MsgId = 1;
  void clear_msgid();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::uint32 msgid() const;
  void set_msgid(::google::protobuf::uint32 value);

  // uint32 SrcAddr = 2;
  void clear_srcaddr();
  static const int kSrcAddrFieldNumber = 2;
  ::google::protobuf::uint32 srcaddr() const;
  void set_srcaddr(::google::protobuf::uint32 value);

  // uint32 DstAddr = 3;
  void clear_dstaddr();
  static const int kDstAddrFieldNumber = 3;
  ::google::protobuf::uint32 dstaddr() const;
  void set_dstaddr(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:core.MsgHead)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 msgid_;
  ::google::protobuf::uint32 srcaddr_;
  ::google::protobuf::uint32 dstaddr_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_core_5fproto_2eproto;
};
// -------------------------------------------------------------------

class MsgBody final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:core.MsgBody) */ {
 public:
  MsgBody();
  virtual ~MsgBody();

  MsgBody(const MsgBody& from);

  inline MsgBody& operator=(const MsgBody& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MsgBody(MsgBody&& from) noexcept
    : MsgBody() {
    *this = ::std::move(from);
  }

  inline MsgBody& operator=(MsgBody&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const MsgBody& default_instance();

  enum StBodyCase {
    kStReqVote = 1,
    kStRspVote = 2,
    STBODY_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgBody* internal_default_instance() {
    return reinterpret_cast<const MsgBody*>(
               &_MsgBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(MsgBody* other);
  friend void swap(MsgBody& a, MsgBody& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MsgBody* New() const final {
    return CreateMaybeMessage<MsgBody>(nullptr);
  }

  MsgBody* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MsgBody>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MsgBody& from);
  void MergeFrom(const MsgBody& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBody* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .core.ReqVote stReqVote = 1;
  bool has_streqvote() const;
  void clear_streqvote();
  static const int kStReqVoteFieldNumber = 1;
  const ::core::ReqVote& streqvote() const;
  ::core::ReqVote* release_streqvote();
  ::core::ReqVote* mutable_streqvote();
  void set_allocated_streqvote(::core::ReqVote* streqvote);

  // .core.RspVote stRspVote = 2;
  bool has_strspvote() const;
  void clear_strspvote();
  static const int kStRspVoteFieldNumber = 2;
  const ::core::RspVote& strspvote() const;
  ::core::RspVote* release_strspvote();
  ::core::RspVote* mutable_strspvote();
  void set_allocated_strspvote(::core::RspVote* strspvote);

  void clear_stBody();
  StBodyCase stBody_case() const;
  // @@protoc_insertion_point(class_scope:core.MsgBody)
 private:
  class HasBitSetters;
  void set_has_streqvote();
  void set_has_strspvote();

  inline bool has_stBody() const;
  inline void clear_has_stBody();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union StBodyUnion {
    StBodyUnion() {}
    ::core::ReqVote* streqvote_;
    ::core::RspVote* strspvote_;
  } stBody_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::TableStruct_core_5fproto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqVote

// uint32 Term = 1;
inline void ReqVote::clear_term() {
  term_ = 0u;
}
inline ::google::protobuf::uint32 ReqVote::term() const {
  // @@protoc_insertion_point(field_get:core.ReqVote.Term)
  return term_;
}
inline void ReqVote::set_term(::google::protobuf::uint32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:core.ReqVote.Term)
}

// uint32 NodeId = 2;
inline void ReqVote::clear_nodeid() {
  nodeid_ = 0u;
}
inline ::google::protobuf::uint32 ReqVote::nodeid() const {
  // @@protoc_insertion_point(field_get:core.ReqVote.NodeId)
  return nodeid_;
}
inline void ReqVote::set_nodeid(::google::protobuf::uint32 value) {
  
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:core.ReqVote.NodeId)
}

// uint64 CommitLogIndex = 3;
inline void ReqVote::clear_commitlogindex() {
  commitlogindex_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ReqVote::commitlogindex() const {
  // @@protoc_insertion_point(field_get:core.ReqVote.CommitLogIndex)
  return commitlogindex_;
}
inline void ReqVote::set_commitlogindex(::google::protobuf::uint64 value) {
  
  commitlogindex_ = value;
  // @@protoc_insertion_point(field_set:core.ReqVote.CommitLogIndex)
}

// -------------------------------------------------------------------

// RspVote

// sint32 Result = 1;
inline void RspVote::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 RspVote::result() const {
  // @@protoc_insertion_point(field_get:core.RspVote.Result)
  return result_;
}
inline void RspVote::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:core.RspVote.Result)
}

// uint32 Term = 2;
inline void RspVote::clear_term() {
  term_ = 0u;
}
inline ::google::protobuf::uint32 RspVote::term() const {
  // @@protoc_insertion_point(field_get:core.RspVote.Term)
  return term_;
}
inline void RspVote::set_term(::google::protobuf::uint32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:core.RspVote.Term)
}

// uint32 NodeId = 3;
inline void RspVote::clear_nodeid() {
  nodeid_ = 0u;
}
inline ::google::protobuf::uint32 RspVote::nodeid() const {
  // @@protoc_insertion_point(field_get:core.RspVote.NodeId)
  return nodeid_;
}
inline void RspVote::set_nodeid(::google::protobuf::uint32 value) {
  
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:core.RspVote.NodeId)
}

// uint32 LeaderId = 4;
inline void RspVote::clear_leaderid() {
  leaderid_ = 0u;
}
inline ::google::protobuf::uint32 RspVote::leaderid() const {
  // @@protoc_insertion_point(field_get:core.RspVote.LeaderId)
  return leaderid_;
}
inline void RspVote::set_leaderid(::google::protobuf::uint32 value) {
  
  leaderid_ = value;
  // @@protoc_insertion_point(field_set:core.RspVote.LeaderId)
}

// -------------------------------------------------------------------

// MsgHead

// uint32 MsgId = 1;
inline void MsgHead::clear_msgid() {
  msgid_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::msgid() const {
  // @@protoc_insertion_point(field_get:core.MsgHead.MsgId)
  return msgid_;
}
inline void MsgHead::set_msgid(::google::protobuf::uint32 value) {
  
  msgid_ = value;
  // @@protoc_insertion_point(field_set:core.MsgHead.MsgId)
}

// uint32 SrcAddr = 2;
inline void MsgHead::clear_srcaddr() {
  srcaddr_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::srcaddr() const {
  // @@protoc_insertion_point(field_get:core.MsgHead.SrcAddr)
  return srcaddr_;
}
inline void MsgHead::set_srcaddr(::google::protobuf::uint32 value) {
  
  srcaddr_ = value;
  // @@protoc_insertion_point(field_set:core.MsgHead.SrcAddr)
}

// uint32 DstAddr = 3;
inline void MsgHead::clear_dstaddr() {
  dstaddr_ = 0u;
}
inline ::google::protobuf::uint32 MsgHead::dstaddr() const {
  // @@protoc_insertion_point(field_get:core.MsgHead.DstAddr)
  return dstaddr_;
}
inline void MsgHead::set_dstaddr(::google::protobuf::uint32 value) {
  
  dstaddr_ = value;
  // @@protoc_insertion_point(field_set:core.MsgHead.DstAddr)
}

// -------------------------------------------------------------------

// MsgBody

// .core.ReqVote stReqVote = 1;
inline bool MsgBody::has_streqvote() const {
  return stBody_case() == kStReqVote;
}
inline void MsgBody::set_has_streqvote() {
  _oneof_case_[0] = kStReqVote;
}
inline void MsgBody::clear_streqvote() {
  if (has_streqvote()) {
    delete stBody_.streqvote_;
    clear_has_stBody();
  }
}
inline ::core::ReqVote* MsgBody::release_streqvote() {
  // @@protoc_insertion_point(field_release:core.MsgBody.stReqVote)
  if (has_streqvote()) {
    clear_has_stBody();
      ::core::ReqVote* temp = stBody_.streqvote_;
    stBody_.streqvote_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::core::ReqVote& MsgBody::streqvote() const {
  // @@protoc_insertion_point(field_get:core.MsgBody.stReqVote)
  return has_streqvote()
      ? *stBody_.streqvote_
      : *reinterpret_cast< ::core::ReqVote*>(&::core::_ReqVote_default_instance_);
}
inline ::core::ReqVote* MsgBody::mutable_streqvote() {
  if (!has_streqvote()) {
    clear_stBody();
    set_has_streqvote();
    stBody_.streqvote_ = CreateMaybeMessage< ::core::ReqVote >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:core.MsgBody.stReqVote)
  return stBody_.streqvote_;
}

// .core.RspVote stRspVote = 2;
inline bool MsgBody::has_strspvote() const {
  return stBody_case() == kStRspVote;
}
inline void MsgBody::set_has_strspvote() {
  _oneof_case_[0] = kStRspVote;
}
inline void MsgBody::clear_strspvote() {
  if (has_strspvote()) {
    delete stBody_.strspvote_;
    clear_has_stBody();
  }
}
inline ::core::RspVote* MsgBody::release_strspvote() {
  // @@protoc_insertion_point(field_release:core.MsgBody.stRspVote)
  if (has_strspvote()) {
    clear_has_stBody();
      ::core::RspVote* temp = stBody_.strspvote_;
    stBody_.strspvote_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::core::RspVote& MsgBody::strspvote() const {
  // @@protoc_insertion_point(field_get:core.MsgBody.stRspVote)
  return has_strspvote()
      ? *stBody_.strspvote_
      : *reinterpret_cast< ::core::RspVote*>(&::core::_RspVote_default_instance_);
}
inline ::core::RspVote* MsgBody::mutable_strspvote() {
  if (!has_strspvote()) {
    clear_stBody();
    set_has_strspvote();
    stBody_.strspvote_ = CreateMaybeMessage< ::core::RspVote >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:core.MsgBody.stRspVote)
  return stBody_.strspvote_;
}

inline bool MsgBody::has_stBody() const {
  return stBody_case() != STBODY_NOT_SET;
}
inline void MsgBody::clear_has_stBody() {
  _oneof_case_[0] = STBODY_NOT_SET;
}
inline MsgBody::StBodyCase MsgBody::stBody_case() const {
  return MsgBody::StBodyCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace core

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_core_5fproto_2eproto
